name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  foundry:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run forge build
        run: forge build
        id: build

      - name: Run forge fmt
        run: forge fmt --check
        id: fmt

      - name: Run forge test
        run: forge test -vvv
        id: test
